# Panes
LEFT_PANE="left-pane"
MAIN_PANE="main-pane"

# Left Pane
ROUTES_LIST="routes-list"

# Main Pane
## New project
NEW_PROJECT="new-project"
NEW_PROJECT_ERROR=f"{NEW_PROJECT}-error"
NEW_PROJECT_ERROR_TITLE=f"{NEW_PROJECT_ERROR}-title"
NEW_PROJECT_ERROR_TITLE_LEFT_CORNER=f"{NEW_PROJECT_ERROR_TITLE}-left-corner"
NEW_PROJECT_ERROR_TITLE_RIGHT_CORNER=f"{NEW_PROJECT_ERROR_TITLE}-right-corner"
NEW_PROJECT_ERROR_TEXT=f"{NEW_PROJECT_ERROR}-text"
NEW_PROJECT_TITLE=f"{NEW_PROJECT}-title"
NEW_PROJECT_TITLE_LEFT_CORNER=f"{NEW_PROJECT_TITLE}-left-corner"
NEW_PROJECT_TITLE_RIGHT_CORNER=f"{NEW_PROJECT_TITLE}-right-corner"
NEW_PROJECT_INPUT=f"{NEW_PROJECT}-input"
NEW_PROJECT_INPUT_FIELD=f"{NEW_PROJECT_INPUT}-field"
NEW_PROJECT_CREATE=f"{NEW_PROJECT}-create"
NEW_PROJECT_CREATE_LEFT_CORNER=f"{NEW_PROJECT_CREATE}-left-corner"
NEW_PROJECT_CREATE_RIGHT_CORNER=f"{NEW_PROJECT_CREATE}-right-corner"
NEW_PROJECT_CREATE_BUTTON=f"{NEW_PROJECT_CREATE}-button"

## Resume Project
RESUME_PROJECT="resume-project"